[Logger]
#максимальное количество сообщений в памяти до сброса в файл
mmax=100
#максимальный размер одного файла в байтах
fsize=1000000
#путь к файлу. Если не задан, то будет лежать рядом с исполняемым файлом
fpath=
#количество файлов в ротации
fnum=3
#уровень логирования (ERROR, WARN, INFO, DEBUG, SPEC)
level=INFO
#ориентировочное время простоя потока логирования (регулируется автоматически), мс
stime=10000

# имена управляемых устройств. Используются как ключи для поиска их параметров
[Devices]
Yamaha=
Samsung=

#Параметров у каждого устройства два
[Yamaha]
#type - справочное значение, зашиты в коды
type=YamahaAVR
ip=RX-V575.local

#Для типа устройства список команд
[YamahaAVR]
HDMI1=<YAMAHA_AV cmd="PUT"><Main_Zone><Input><Input_Sel>HDMI1</Input_Sel></Input></Main_Zone></YAMAHA_AV>
HDMI2=<YAMAHA_AV cmd="PUT"><Main_Zone><Input><Input_Sel>HDMI2</Input_Sel></Input></Main_Zone></YAMAHA_AV>
VOLUMEUP=<YAMAHA_AV cmd="PUT"><Main_Zone><Volume><Lvl><Val>Up 1 dB</Val><Exp></Exp><Unit></Unit></Lvl></Volume></Main_Zone></YAMAHA_AV>
VOLUMEDOWN=<YAMAHA_AV cmd="PUT"><Main_Zone><Volume><Lvl><Val>Down 1 dB</Val><Exp></Exp><Unit></Unit></Lvl></Volume></Main_Zone></YAMAHA_AV>
MUTE=<YAMAHA_AV cmd="PUT"><Main_Zone><Volume><Mute>On/Off</Mute></Volume></Main_Zone></YAMAHA_AV>
ON=<YAMAHA_AV cmd="PUT"><Main_Zone><Power_Control><Power>On</Power></Power_Control></Main_Zone></YAMAHA_AV>
OFF=<YAMAHA_AV cmd="PUT"><Main_Zone><Power_Control><Power>Standby</Power></Power_Control></Main_Zone></YAMAHA_AV>
DSP_7CH=<YAMAHA_AV cmd="PUT"><Main_Zone><Surround><Program_Sel><Current><Sound_Program>7ch Stereo</Sound_Program></Current></Program_Sel></Surround></Main_Zone></YAMAHA_AV>
GET=<YAMAHA_AV cmd="GET"><Main_Zone><Basic_Status>GetParam</Basic_Status></Main_Zone></YAMAHA_AV>
GET_CONF=<YAMAHA_AV cmd="GET"><System><Config>GetParam</Config></System></YAMAHA_AV>

[Samsung]
type=SamsungOldTV
ip=192.168.0.100

[SamsungOldTV]
HDMI=KEY_HDMI
TV=KEY_TV
VOLUMEUP=KEY_VOLUP
VOLUMEDOWN=KEY_VOLDOWN
CHANNELUP=KEY_CHUP
CHANNELDOWN=KEY_CHDOWN
MUTE=KEY_MUTE
OFF=KEY_POWEROFF

